# Generated by Django 4.1 on 2023-12-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Data')),
                ('hour', models.CharField(max_length=5, verbose_name='Hora')),
                ('status', models.CharField(max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Adocao',
                'verbose_name_plural': 'Adocoes',
                'ordering': ['id'],
            },
        ),
    ]
