# Generated by Django 4.1 on 2023-12-08 03:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animais', '0001_initial'),
        ('adotantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('date_hour', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data e Hora da Adoção')),
                ('adopter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adotantes.adotante')),
                ('animal', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='animais.animal')),
            ],
            options={
                'verbose_name': 'Adocao',
                'verbose_name_plural': 'Adocoes',
                'ordering': ['id'],
            },
        ),
    ]
