# Generated by Django 4.1 on 2023-12-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adocao',
            name='date_hour',
            field=models.DateTimeField(verbose_name='Data e Hora da Adoção'),
        ),
    ]
