# Generated by Django 4.1 on 2023-12-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0002_alter_adocao_date_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adocao',
            name='date_hour',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Adoção'),
        ),
    ]
