# Generated by Django 4.1 on 2023-12-07 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adotantes', '0001_initial'),
        ('adocoes', '0002_rename_hour_adocao_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adocao',
            name='status',
        ),
        migrations.AddField(
            model_name='adocao',
            name='adopter',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='adotantes.adotante'),
        ),
        migrations.AlterField(
            model_name='adocao',
            name='date',
            field=models.CharField(max_length=10, verbose_name='Data'),
        ),
    ]
