# Generated by Django 4.1 on 2023-12-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0003_adocao_adopter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adocao',
            name='date',
            field=models.CharField(max_length=10, verbose_name='Data'),
        ),
    ]
