# Generated by Django 4.1 on 2023-12-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0004_alter_adocao_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adocao',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('adotado', 'Adotado')], default='disponivel', max_length=10, verbose_name='Status'),
        ),
    ]
