# Generated by Django 4.1 on 2023-12-08 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veterinarios', '0001_initial'),
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=50, verbose_name='Razao')),
                ('description', models.CharField(max_length=50, verbose_name='Descricao')),
                ('medicine', models.CharField(max_length=15, verbose_name='Medicamento')),
                ('vaccine', models.CharField(max_length=15, verbose_name='Vacina')),
                ('animal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='animais.animal')),
                ('veterinary', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='veterinarios.veterinario')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ['id'],
            },
        ),
    ]
