# Generated by Django 4.1 on 2023-12-07 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adocoes', '0002_rename_hour_adocao_time'),
        ('animais', '0006_alter_animal_donator_alter_animal_ong'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adocaoanimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('adoption', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adocoes.adocao')),
                ('animal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='animais.animal')),
            ],
            options={
                'verbose_name': 'Adocaoanimal',
                'verbose_name_plural': 'Adocaoanimais',
                'ordering': ['id'],
            },
        ),
    ]
