# Generated by Django 4.1 on 2023-12-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adocaoanimais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adocaoanimal',
            name='adoption',
        ),
    ]
