# Generated by Django 4.1 on 2023-11-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('address', models.TextField(max_length=100, verbose_name='Endereco')),
                ('phone', models.TextField(max_length=20, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Ong',
                'verbose_name_plural': 'Ongs',
                'ordering': ['id'],
            },
        ),
    ]
