# Generated by Django 4.1 on 2023-12-08 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ongs', '0001_initial'),
        ('doadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('sex', models.CharField(choices=[('macho', 'Macho'), ('femea', 'Fêmea')], default='macho', max_length=5, verbose_name='Sexo')),
                ('years_old_value', models.PositiveIntegerField(default=0, verbose_name='Idade')),
                ('years_old_unit', models.CharField(choices=[('anos', 'Anos'), ('meses', 'Meses')], default='meses', max_length=10, verbose_name='Unidade de Idade')),
                ('specie', models.CharField(choices=[('gato', 'Gato'), ('cachorro', 'Cachorro')], default='cachorro', max_length=10, verbose_name='Especie')),
                ('race', models.CharField(max_length=10, verbose_name='Raca')),
                ('color', models.CharField(max_length=10, verbose_name='Cor')),
                ('weight_value', models.PositiveIntegerField(default=0, verbose_name='Peso')),
                ('weight_unit', models.CharField(choices=[('gramas', 'Gramas'), ('quilos', 'Quilos')], default='gramas', max_length=10, verbose_name='Unidade de Peso')),
                ('height_value', models.PositiveIntegerField(default=0, verbose_name='Altura')),
                ('height_unit', models.CharField(choices=[('centimetros', 'Centímetros'), ('metros', 'Metros')], default='metros', max_length=11, verbose_name='Unidade de Altura')),
                ('donator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doadores.doador')),
                ('ong', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ongs.ong')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['id'],
            },
        ),
    ]
