# Generated by Django 4.1 on 2023-12-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('sex', models.CharField(max_length=5, verbose_name='Sexo')),
                ('years_old', models.CharField(max_length=2, verbose_name='Idade')),
                ('species', models.CharField(max_length=10, verbose_name='Especie')),
                ('race', models.CharField(max_length=10, verbose_name='Raca')),
                ('color', models.CharField(max_length=10, verbose_name='Cor')),
                ('weight', models.CharField(max_length=2, verbose_name='Peso')),
                ('height', models.CharField(max_length=3, verbose_name='Altura')),
                ('adoption_status', models.CharField(max_length=10, verbose_name='Status adocao')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['id'],
            },
        ),
    ]
