# Generated by Django 4.1 on 2023-12-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], default='Macho', max_length=5, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='specie',
            field=models.CharField(choices=[('Gato', 'Gato'), ('Cachorro', 'Cachorro')], default='Cachorro', max_length=10, verbose_name='Especie'),
        ),
    ]
