# Generated by Django 4.1 on 2023-12-02 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='species',
            new_name='specie',
        ),
    ]
