# Generated by Django 4.1 on 2023-12-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_rename_species_animal_specie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='adoption_status',
            field=models.CharField(max_length=10, verbose_name='Status_adocao'),
        ),
    ]
