# Generated by Django 4.1 on 2023-12-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0003_alter_animal_adoption_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='adoption_status',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='height',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='years_old',
        ),
        migrations.AddField(
            model_name='animal',
            name='height_unit',
            field=models.CharField(choices=[('centimetros', 'Centímetros'), ('metros', 'Metros')], default='metros', max_length=11, verbose_name='Unidade de Altura'),
        ),
        migrations.AddField(
            model_name='animal',
            name='height_value',
            field=models.PositiveIntegerField(default=0.0, verbose_name='Altura'),
        ),
        migrations.AddField(
            model_name='animal',
            name='weight_unit',
            field=models.CharField(choices=[('gramas', 'Gramas'), ('quilos', 'Quilos')], default='gramas', max_length=10, verbose_name='Unidade de Peso'),
        ),
        migrations.AddField(
            model_name='animal',
            name='weight_value',
            field=models.PositiveIntegerField(default=0.0, verbose_name='Peso'),
        ),
        migrations.AddField(
            model_name='animal',
            name='years_old_unit',
            field=models.CharField(choices=[('anos', 'Anos'), ('meses', 'Meses')], default='meses', max_length=10, verbose_name='Unidade de Idade'),
        ),
        migrations.AddField(
            model_name='animal',
            name='years_old_value',
            field=models.PositiveIntegerField(default=0.0, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('macho', 'Macho'), ('femea', 'Fêmea')], default='macho', max_length=5, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='specie',
            field=models.CharField(choices=[('gato', 'Gato'), ('cachorro', 'Cachorro')], default='cachorro', max_length=10, verbose_name='Especie'),
        ),
    ]
