# Generated by Django 4.1 on 2023-12-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0006_alter_animal_donator_alter_animal_ong'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('adotado', 'Adotado')], default='disponivel', max_length=10, verbose_name='Status'),
        ),
    ]
