# Generated by Django 4.1 on 2023-12-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='Cpf'),
        ),
        migrations.AlterField(
            model_name='doador',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Telefone'),
        ),
    ]
