# Generated by Django 4.1 on 2023-11-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='ong',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Telefone'),
        ),
    ]
